; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

; =============================================
; TEST CONFIGURATIONS
; =============================================

[env:esp8266_test]
platform = espressif8266
board = esp07
framework = arduino

board_build.flash_mode = dout
board_build.f_cpu = 80000000L

upload_speed = 115200
upload_resetmethod = ck
monitor_speed = 9600
monitor_filters = direct
monitor_dtr = 0
monitor_rts = 0

build_flags = -v -DCHIPTYPE=ESP8266
build_src_filter = -<*.cpp> +<z_main_test.cpp>

[env:esp32_test]
platform = espressif32
board = esp32dev
framework = arduino
src_filter = +<z_main_test.cpp>
upload_protocol = esptool
upload_speed = 9600
upload_port = /dev/ttyUSB0
upload_flags = 
    --before=no_reset
    --after=hard_reset
    --chip=esp32
    --baud=9600
monitor_port = /dev/ttyUSB0
board_upload.require_upload_port = false
board_upload.before_reset = no_reset
board_upload.after_reset = hard_reset
board_upload.use_1200bps_touch = false
board_upload.wait_for_upload_port = true
board_build.flash_mode = dio
board_build.flash_size = 4MB
monitor_speed = 9600
monitor_filters = direct

build_flags = -v -DCHIPTYPE=ESP32
build_src_filter = -<*.cpp> +<z_main_test.cpp>

; =============================================
; ESP8266 CONFIGURATIONS
; =============================================

[env:misto_setup]
platform = espressif8266
board = esp07
framework = arduino

board_build.flash_mode = dout
board_build.f_cpu = 80000000L

upload_speed = 115200
upload_resetmethod = ck
monitor_speed = 9600
monitor_filters = direct
monitor_dtr = 0
monitor_rts = 0

build_flags = -v -DCHIPTYPE=ESP8266 -DPUBSUBCLIENT_MAX_PACKET_SIZE=512
build_src_filter = -<*.cpp> +<z_main_misto_setup.cpp>
	+<boxsecrets.cpp> +<MqttPublisher.cpp> 
	+<DiscoveryMsg.cpp> +<DhtSensor.cpp> +<Publisher.cpp>
	+<ConfigFile.cpp>
lib_deps = 
	bblanchon/ArduinoJson
	adafruit/DHT sensor library
	adafruit/Adafruit Unified Sensor
	knolleary/PubSubClient

[env:misto_real]
platform = espressif8266
board = esp07
framework = arduino

upload_speed = 115200
upload_resetmethod = ck
monitor_speed = 9600
monitor_dtr = 0
monitor_rts = 0

build_flags = -v -DCHIPTYPE=ESP8266 -DPUBSUBCLIENT_MAX_PACKET_SIZE=1024
build_src_filter = -<*.cpp> +<z_main_misto.cpp> +<MqttPublisher.cpp> 
	+<DiscoveryMsg.cpp> +<DhtSensor.cpp> +<boxsecrets.cpp> 	
	+<LedBlinker.cpp> +<DiscoveryClient.cpp> +<Publisher.cpp>
lib_deps = 
	tzapu/WiFiManager
	bblanchon/ArduinoJson
	adafruit/DHT sensor library
	adafruit/Adafruit Unified Sensor
	knolleary/PubSubClient

[env:apiscale_lite_setup]
platform = espressif8266
board = esp07
framework = arduino

board_build.flash_mode = dout
board_build.f_cpu = 80000000L

upload_speed = 115200
upload_resetmethod = ck
monitor_speed = 9600
monitor_filters = direct
monitor_dtr = 0
monitor_rts = 0

build_flags = -v -DCHIPTYPE=ESP8266 -DPUBSUBCLIENT_MAX_PACKET_SIZE=512
build_src_filter = -<*.cpp> +<z_main_apiscale_lite.cpp>
	+<boxsecrets.cpp> +<MqttPublisher.cpp> 
	+<DiscoveryMsg.cpp> +<DhtSensor.cpp> +<Publisher.cpp>
	+<ConfigFile.cpp> +<Hx711Sensor.cpp>
lib_deps = 
	bblanchon/ArduinoJson
	adafruit/DHT sensor library
	adafruit/Adafruit Unified Sensor
	knolleary/PubSubClient
	bogde/HX711@^0.7.5

[env:cat_toy]
platform = espressif8266
board = esp07
framework = arduino

board_build.flash_mode = dout
board_build.flash_size = 1MB

upload_speed = 115200
upload_resetmethod = ck
monitor_speed = 115200
monitor_dtr = 0
monitor_rts = 0

build_src_filter = -<*.cpp> +<z_main_cattoy.cpp> +<Adxl345Sensor.cpp>
	+<MqttPublisher.cpp> 
	+<DiscoveryMsg.cpp> 
	+<LedBlinker.cpp> +<DiscoveryClient.cpp> +<Publisher.cpp>
lib_deps = 
	tzapu/WiFiManager
	bblanchon/ArduinoJson
	knolleary/PubSubClient

[env:cat_toy_setup]
platform = espressif8266
board = esp07
framework = arduino

board_build.flash_mode = dout
board_build.flash_size = 1MB

upload_speed = 115200
upload_resetmethod = ck
monitor_speed = 115200
monitor_dtr = 0
monitor_rts = 0

build_src_filter = -<*.cpp> 
	+<z_main_cattoy_setup.cpp>
	+<Adxl345Sensor.cpp>
	+<MqttPublisher.cpp>
	+<WiFiManagerParams.cpp>
	+<boxsecrets.cpp>
lib_deps = 
	bblanchon/ArduinoJson
	tzapu/WiFiManager
	knolleary/PubSubClient

; =============================================
; ESP32 CONFIGURATIONS
; =============================================

[env:esp32_remote_setup]
platform = espressif32
board = esp32dev
framework = arduino
build_flags = -v -DCHIPTYPE=ESP32 -DPUBSUBCLIENT_MAX_PACKET_SIZE=512
build_src_filter = -<*.cpp> +<z_main_32_remote_setup.cpp>
	+<HaRemoteClient.cpp> +<DiscoveryMsg.cpp> +<DhtSensor.cpp>
	+<boxsecrets.cpp> +<LedBlinker.cpp> +<ConfigFile.cpp> +<Hx711Sensor.cpp>
lib_deps = 
	bblanchon/ArduinoJson
	adafruit/DHT sensor library
	adafruit/Adafruit Unified Sensor
	bogde/HX711@^0.7.5
	ricaun/ArduinoUniqueID @ ^1.2.0

[env:apiscale_real]
platform = espressif32
board = esp32dev
framework = arduino
build_flags = -v -DCHIPTYPE=ESP32 -DPUBSUBCLIENT_MAX_PACKET_SIZE=512
build_src_filter = -<*.cpp> +<z_main_apiscale.cpp>
	+<MqttPublisher.cpp> +<DiscoveryMsg.cpp> +<DhtSensor.cpp>
	+<boxsecrets.cpp> +<LedBlinker.cpp> +<ConfigFile.cpp> +<Hx711Sensor.cpp>
	+<WiFiManagerParams.cpp> +<Publisher.cpp>
lib_deps = 
	bblanchon/ArduinoJson
	adafruit/DHT sensor library
	adafruit/Adafruit Unified Sensor
	bogde/HX711@^0.7.5
	ricaun/ArduinoUniqueID @ ^1.2.0
 