
# Example of messages used by the sensor-devices




## The Device Discovery Message

This is the pattern for the discovery-msg sent to Homeassistant at sensor set-up. It is sent with the retain-flag set to true so it will be stored in the mqtt-broker and sent to Homeassistant at start-up.
The sensor sends the message to the following topic:
homeassistant/sensor/sw_<devid>-<dclass>/config
with the following format and content for each device entity (sensor):

[source,json]
----
{
    "name": "<devid>-<dclass>",
    "state_topic": "home/sensor/sw_<devid>",
    "unit_of_measurement": "<unit>",
    "device_class": "<dclass>",
    "value_template": "{{ value_json.<dclass> }}",
    "unique_id": "sw_<devid>-<dclass>",
    "device": {
        "identifiers": [
            "sw_<devid>"
        ],
        "manufacturer": "www.sensorwebben.se",
        "model": "Sensor Model GDC",
        "sw_version": "2.2.1"
    }
}
----

## The Device Publish Message
The publish message with data from the device is sent to the topic home/sensor/sw_<devid> and contains the following type of content:

[source,json]
----
{
        "temperature": 42,
        "humidity": 5,
        "battery": 3.932,
        "abat": 582,
        "rssi": "-66",
        "wifitries": 2,
        "mqtttries": 1,
        "localip": "192.168.68.101",
        "ssid": "dlink-4ECC"
    }
----

## The Device Configuration Message
The configuration message is sent from Home Assistant to the topic home/sensor/sw_<devid>/config 

It is sent with the retain-flag set to true so it will be stored in the mqtt-broker and sent to the device when the device start-up for the next measuring cycle.
The values will then be stored in the device and used for the next publish message.

The configuration message contains the following type of content:
[source,json]
----
{
    {
        "sleeptime": 10,
        "any-other-future-setting": "value"
        
    }
}